openapi: 3.1.0
info:
  title: Fédération de Collectivités Agircoles
  description: API de gestion de la fédération agricole à Madagascar
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:

  /adhesions:
    $ref: './paths/Membres.yaml#/adhesions'
  /adhesions/{id}:
    $ref: './paths/Membres.yaml#/adhesions_id'
  /adhesions/{id}/paiement:
    $ref: './paths/Membres.yaml#/paiements'
  /membres/{id}:
    $ref: './paths/Membres.yaml#/membres_id'
  /membres/{id}/transferts:
    $ref: './paths/Membres.yaml#/transferts'
  /membres/{id}/demission:
    $ref: './paths/Membres.yaml#/demissions'
  /membres/{id}/historique-collectivites:
    $ref: './paths/Membres.yaml#/historique'
  /collectivites/{id}/membres:
    $ref: './paths/Membres.yaml#/collectivite_membres'
