openapi: 3.0.0
info:
  title: Fédération de Collectivités Agricoles
  description: API de gestion de la fédération agricole à Madagascar
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /adhesions:
    $ref: './paths/B/Adhesions.yaml'
  /adhesions/{id}:
    $ref: './paths/B/AdhesionsId.yaml'
  /adhesions/{id}/paiement:
    $ref: './paths/B/AdhesionsPaiement.yaml'
  /membres/{id}:
    $ref: './paths/B/MembresId.yaml'
  /membres/{id}/transferts:
    $ref: './paths/B/MembresTransferts.yaml'
  /membres/{id}/demission:
    $ref: './paths/B/MembresDemission.yaml'
  /membres/{id}/historique-collectivites:
    $ref: './paths/B/MembresHistorique.yaml'
  /collectivites/{id}/membres:
    $ref: './paths/B/CollectivitesMembres.yaml'


